### ISSUE TITLE
check_logservice.py: Exception Handling on Network error

### ISSUE THREAD

**Issue by daugustin** [EXASOL/nagios-monitoring#12]
Hi,

when a "network" error occurs, the check_logservice.py throws an exception

```
[Traceback (most recent call last):

  File /usr/lib64/nagios/plugins/check_exasol_logservice.py, line 106, in module
    logEntries = logservice.logEntriesTagged(logserviceUserId)
  File /usr/lib64/python2.6/xmlrpclib.py, line 1199, in __call__
    return self.__send(self.__name, args)
  File /usr/lib64/python2.6/xmlrpclib.py, line 1489, in __request
    verbose=self.__verbose
  File /usr/lib64/python2.6/xmlrpclib.py, line 1243, in request
    headers
xmlrpclib.ProtocolError: ProtocolError for monitoring:PW@somehostname/cluster1/logservice3: 501 Gateway error]
```

This has 2 problems:

- It echos the monitoring password to stdout. If using nagios/icinga/... this will be included in the notification.
- The error itself, maybe a random network problem, should be ignored alltogether. This is a logservice check and thus should only output real errors. Maybe this exception could result in the UNKNOWN state (return code 3). The current state results in CRTICAL which cant be dinstinguished from real errors. There are other checks that check the global state of the cluster, so I think this should be ignored all together.

**Comment by florian-reck** [comment]
This bug should be fixed with the newest version of this plugin. Can you please check again?

**Comment by daugustin** [comment]
I ran a git pull on the plugins now, we will monitor if the problem arises again.

**Comment by florian-reck** [comment]
reopen on demand ;)
