### ISSUE TITLE
Query-Performance Monitoring

### ISSUE THREAD

**Issue by exaSR** [exasol/nagios-monitoring#25]
As discussed, it would be great to have some way to
- define (one or more) SQL statements (for a given database)
- define expected and critical reaction times
- define probing interval

Such that Nagios
- automatically executes the queries
- tracks response times 
- renders them in a graph
- sends out alerts when response times exceed the defined threshold

**Comment by florian-reck** [comment]
Created an Exasol internal issue to create this new plugin;
