### ISSUE TITLE
SNMP iRMC --chkstorage no result

### ISSUE THREAD

**Issue by bitboy85** [exasol/nagios-monitoring#49]
I'm checking our PRIMERGY RX2540 M1 via iRMC SNMP and if i try to get RAID information using --chkstorage ist says:

> UNKNOWN - No RAID or other MassStorage - 

iRMC Version is
Firmware Version: 8.08F (Base: 8.08.F)
Nov 26 2015 - 22:39:19 CET
Low Firmware Image
3.64 ID 0416 RX2540M1

**Comment by florian-reck** [comment]
I need a little bit more input:

* Exasol version
* which Exasol FSC Plugin version has been used?
* the snmpd.conf which was deployed on the cluster

**Comment by bitboy85** [comment]
I have upgraded the iRMC Firmware to 9.20F (Base: 9.20.F). Its working now.
