### ISSUE TITLE
Question: Nagios plugins usable on own Nagios installation?

### ISSUE THREAD

**Issue by ChristianGfK** [exasol/nagios-monitoring#50]
Hi,

more of a question than an issue:
Are the Nagios check plugins [here ](https://github.com/exasol/nagios-monitoring/tree/master/opt/exasol/monitoring) and [described here](https://github.com/EXASOL/nagios-monitoring/wiki/Plugin-Descriptions) for use with your own regular Nagios/Icinga installation, or only for this pre-configured Exasol Nagios bundle?

Or, maybe I could have gotten to this realization sooner:
Is this whole bundle just the above plugins + some scaffolding to make it easy to use, and I should spend my time trying to integrate the plugins into our existing Nagios setup instead of creating a second one (this one)? 🤔 

Best regards
Christian

**Comment by florian-reck** [comment]
Hi Christian,

those plugins can be used in every monitoring system which supports the Nagios Plugin API (https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/pluginapi.html), so they work together with Icinga too. The only thing necessary is Python 3.5 or newer, the plugins can even be used under Microsoft Windows.

The easiest way to download them with with their dependencies is PyPI:
`python3 -m pip install --upgrade ExasolMonitoringPlugins`

**Comment by ChristianGfK** [comment]
I see, thanks!
