### ISSUE TITLE
Hardware monitoring plugins

### ISSUE THREAD

**Issue by ChristianGfK** [exasol/nagios-monitoring#51]
Hi,

maybe I am missing the point of some or all of the things provided here, but:
What exactly is the intended end result of installing the nagios bundle + for example the Dell plugin?
Should the hardware status(es) be reported in the nagios installation?
Does it just provide some way of accessing the hardware information (from what I can gather, via snmpd running on the DB nodes)?
If so, how? The servers do not reply to SNMP requests... probably firewalled?

Either way, I managed to install the Dell plugin via XML-RPC manually, and also using the `create-snmp-config` script, but in the end, I fail to see any usable result?

I assume I'm doing something wrong, but I'm unclear on what that might be.

**Comment by florian-reck** [comment]
Hi Christian,

Q: What exactly is the intended end result of installing the nagios bundle + for example the Dell plugin?
A: Endresult should be to monitor the whole stack starting with the hardware. The DELL plugin for instance shows you, if a RAM DIMM fails and which one or will inform you about degraded RAIDs so you can change the hardware before having outtages.

It seems that after installing any of those SNMP monitoring plugins that ExaOperation starts them within the wrong kernel namespace and then they are disfunctional. This seems to be a bug in ExaOperation itself and cannot changed from outside via XMLRPC.

**Comment by florian-reck** [comment]
I suggest you to open a bug ticket on our Exasol support tracker (www.exasol.com/support) and tell them, that you are not able to use the current hardware plugins because they doesn't seem to work.
