### ISSUE TITLE
RHEL6: check_db_performance.py does not work

### ISSUE THREAD

**Issue by daugustin** [EXASOL/nagios-monitoring#9]
Hi,

when I try to call check_db_performance.py on RHEL6 with pyodbc and unixODBC installed, I get the following error:

```
./check_db_performance.py -H <somehost> -u monitoring -p <somepw> -d <somedb> -l sys -a <somepw> 
('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnectW)')
```

The Exasol ODBC driver is at

```
/opt/exasol/EXASOL_ODBC-6.0.0/lib/linux/x86_64/libexaodbc-uo2214lv2.so
```

and ldd shows no error about libs.

**Comment by florian-reck** [comment]
Hi,

We'll check that and come back to you as soon as we can provide results for this.

**Comment by florian-reck** [comment]
I tried it in a fresh CentOS 6.9 with EPEL (unixODBC + pyODBC installed). You need to add the following lines to your /etc/odbcinst.ini file:

```
[exasolution-uo2214lv2_64]
DRIVER = /opt/exasol/EXASOL_ODBC-6.0.4/lib/linux/x86_64/libexaodbc-uo2214lv2.so

[exasolution-uo2214lv2_64-debug]
DRIVER = /opt/exasol/EXASOL_ODBC-6.0.4/lib/linux/x86_64/libexaodbc-uo2214lv2.so
EXAHOST = 10.70.0.71..75:8563
EXALOGFILE = /opt/exasol/EXASOL_ODBC-6.0.4/exaodbc.log
LOGMODE = verbose
```
You may need to correct the path to your ODBC driver libraries. The second entry is optional and only interessting if you need ODBC log files from the ODBC driver.

With the new version 17.11.2 of the check_db_performance.py plugin a new parameter has been introduced:  -o <ODBC driver name>

The following command should work for you:
```
./check_db_performance.py -H <somehost> -u monitoring -p <somepw> -d <somedb> -l sys -a <somepw> -o "exasolution-uo2214lv2_64"
```

Please give us some feedback, if this fixes your problem or not.

Kind regards,
Flo

**Comment by daugustin** [comment]
The check works now. Thank you.
